from . import project
from . import building
from . import apartment
from . import product_template
from . import sale_order
from . import account_move
from . import stock_picking
from . import apartment_actions
from . import res_partner
from . import res_users
